### ISSUE TITLE
imcompaiblity with bewitchment mod

### ISSUE THREAD

**Issue by Bob3DPaint** [AranaiRa/ArcaneArchives#83]
arcanearchives-0.2.0.14
bewitchment-1.12.2-0.0.21.7.jar

MCMulti Report

MultiMC version: 0.6.7-1375

Minecraft folder is:
I:/MC/mmc-stable-win32/MultiMC/instances/1.12.23/.minecraft

Java path is:
C:/Program Files/Java/jre1.8.0_181/bin/javaw.exe

Java is version 1.8.0_181, using 64-bit architecture.

Main Class:
  net.minecraft.launchwrapper.Launch

Native path:
  I:/MC/mmc-stable-win32/MultiMC/instances/1.12.23/natives

Libraries:
  I:/MC/mmc-stable-win32/MultiMC/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
  I:/MC/mmc-stable-win32/MultiMC/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
  I:/MC/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl/2.9.4-nightly-20150209/lwjgl-2.9.4-nightly-20150209.jar
  I:/MC/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.4-nightly-20150209/lwjgl_util-2.9.4-nightly-20150209.jar
  I:/MC/mmc-stable-win32/MultiMC/libraries/com/mojang/patchy/1.1/patchy-1.1.jar
  I:/MC/mmc-stable-win32/MultiMC/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar
  I:/MC/mmc-stable-win32/MultiMC/libraries/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar
  I:/MC/mmc-stable-win32/MultiMC/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar
  I:/MC/mmc-stable-win32/MultiMC/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar
  I:/MC/mmc-stable-win32/MultiMC/libraries/net/sf/jopt-simple/jopt-simple/5.0.3/jopt-simple-5.0.3.jar
  I:/MC/mmc-stable-win32/MultiMC/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar
  I:/MC/mmc-stable-win32/MultiMC/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar
  I:/MC/mmc-stable-win32/MultiMC/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar
  I:/MC/mmc-stable-win32/MultiMC/libraries/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar
  I:/MC/mmc-stable-win32/MultiMC/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar
  I:/MC/mmc-stable-win32/MultiMC/libraries/io/netty/netty-all/4.1.9.Final/netty-all-4.1.9.Final.jar
  I:/MC/mmc-stable-win32/MultiMC/libraries/com/google/guava/guava/21.0/guava-21.0.jar
  I:/MC/mmc-stable-win32/MultiMC/libraries/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar
  I:/MC/mmc-stable-win32/MultiMC/libraries/commons-io/commons-io/2.5/commons-io-2.5.jar
  I:/MC/mmc-stable-win32/MultiMC/libraries/commons-codec/commons-codec/1.10/commons-codec-1.10.jar
  I:/MC/mmc-stable-win32/MultiMC/libraries/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar
  I:/MC/mmc-stable-win32/MultiMC/libraries/com/mojang/authlib/1.5.25/authlib-1.5.25.jar
  I:/MC/mmc-stable-win32/MultiMC/libraries/com/mojang/realms/1.10.22/realms-1.10.22.jar
  I:/MC/mmc-stable-win32/MultiMC/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  I:/MC/mmc-stable-win32/MultiMC/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  I:/MC/mmc-stable-win32/MultiMC/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  I:/MC/mmc-stable-win32/MultiMC/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  I:/MC/mmc-stable-win32/MultiMC/libraries/it/unimi/dsi/fastutil/7.1.0/fastutil-7.1.0.jar
  I:/MC/mmc-stable-win32/MultiMC/libraries/org/apache/logging/log4j/log4j-api/2.8.1/log4j-api-2.8.1.jar
  I:/MC/mmc-stable-win32/MultiMC/libraries/org/apache/logging/log4j/log4j-core/2.8.1/log4j-core-2.8.1.jar
  I:/MC/mmc-stable-win32/MultiMC/libraries/com/mojang/text2speech/1.10.3/text2speech-1.10.3.jar
  I:/MC/mmc-stable-win32/MultiMC/libraries/net/minecraftforge/forge/1.12.2-14.23.5.2847/forge-1.12.2-14.23.5.2847-universal.jar
  I:/MC/mmc-stable-win32/MultiMC/libraries/net/minecraft/launchwrapper/1.12/launchwrapper-1.12.jar
  I:/MC/mmc-stable-win32/MultiMC/libraries/org/ow2/asm/asm-all/5.2/asm-all-5.2.jar
  I:/MC/mmc-stable-win32/MultiMC/libraries/org/jline/jline/3.5.1/jline-3.5.1.jar
  I:/MC/mmc-stable-win32/MultiMC/libraries/com/typesafe/akka/akka-actor_2.11/2.3.3/akka-actor_2.11-2.3.3.jar
  I:/MC/mmc-stable-win32/MultiMC/libraries/com/typesafe/config/1.2.1/config-1.2.1.jar
  I:/MC/mmc-stable-win32/MultiMC/libraries/org/scala-lang/scala-actors-migration_2.11/1.1.0/scala-actors-migration_2.11-1.1.0.jar
  I:/MC/mmc-stable-win32/MultiMC/libraries/org/scala-lang/scala-compiler/2.11.1/scala-compiler-2.11.1.jar
  I:/MC/mmc-stable-win32/MultiMC/libraries/org/scala-lang/plugins/scala-continuations-library_2.11/1.0.2/scala-continuations-library_2.11-1.0.2.jar
  I:/MC/mmc-stable-win32/MultiMC/libraries/org/scala-lang/plugins/scala-continuations-plugin_2.11.1/1.0.2/scala-continuations-plugin_2.11.1-1.0.2.jar
  I:/MC/mmc-stable-win32/MultiMC/libraries/org/scala-lang/scala-library/2.11.1/scala-library-2.11.1.jar
  I:/MC/mmc-stable-win32/MultiMC/libraries/org/scala-lang/scala-parser-combinators_2.11/1.0.1/scala-parser-combinators_2.11-1.0.1.jar
  I:/MC/mmc-stable-win32/MultiMC/libraries/org/scala-lang/scala-reflect/2.11.1/scala-reflect-2.11.1.jar
  I:/MC/mmc-stable-win32/MultiMC/libraries/org/scala-lang/scala-swing_2.11/1.0.1/scala-swing_2.11-1.0.1.jar
  I:/MC/mmc-stable-win32/MultiMC/libraries/org/scala-lang/scala-xml_2.11/1.0.2/scala-xml_2.11-1.0.2.jar
  I:/MC/mmc-stable-win32/MultiMC/libraries/lzma/lzma/0.0.1/lzma-0.0.1.jar
  I:/MC/mmc-stable-win32/MultiMC/libraries/java3d/vecmath/1.5.2/vecmath-1.5.2.jar
  I:/MC/mmc-stable-win32/MultiMC/libraries/net/sf/trove4j/trove4j/3.0.3/trove4j-3.0.3.jar
  I:/MC/mmc-stable-win32/MultiMC/libraries/org/apache/maven/maven-artifact/3.5.3/maven-artifact-3.5.3.jar
  I:/MC/mmc-stable-win32/MultiMC/libraries/com/mojang/minecraft/1.12.2/minecraft-1.12.2-client.jar

Native libraries:
  I:/MC/mmc-stable-win32/MultiMC/libraries/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-windows.jar
  I:/MC/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl-platform/2.9.4-nightly-20150209/lwjgl-platform-2.9.4-nightly-20150209-natives-windows.jar
  I:/MC/mmc-stable-win32/MultiMC/libraries/com/mojang/text2speech/1.10.3/text2speech-1.10.3-natives-windows.jar

Mods:
  [📁] 1.12 (folder)
  [❌] AbyssalCraft Integration-1.12.2-1.9.0.jar (disabled)
  [❌] AbyssalCraft-1.12.2-1.9.15.jar (disabled)
  [❌] AdditionalBanners-1.12.2-1.1.76.jar (disabled)
  [❌] AncientSpellcraft-1.12.2-1.0.1.jar (disabled)
  [❌] ancientwarfare-1.12.2-2.7.0.772.jar (disabled)
  [❌] antiqueatlas-1.12.2-4.6.3.jar (disabled)
  [❌] anvilpatch-1.0.0.jar (disabled)
  [❌] Apotheosis-1.12.2-1.12.4.jar (disabled)
  [❌] Arcane Essentials-0.9.2.jar (disabled)
  [✔️] arcanearchives-0.2.0.14
  [❌] arcaneworld-1.12.2-0.0.12.jar (disabled)
  [❌] arcanum-1.12.2-4.3.0.0.jar (disabled)
  [❌] architecturecraft-1.12-3.98.jar (disabled)
  [❌] astralsorcery-1.12.2-1.10.21.jar (disabled)
  [❌] AttributeFix-1.12.2-1.0.4.jar (disabled)
  [❌] Atum-1.12.2-2.0.16.jar (disabled)
  [❌] AutoRegLib-1.3-32.jar (disabled)
  [❌] BackTools-1.12.2-7.0.1.jar (disabled)
  [❌] Baublelicious-1.4.0-4.jar (disabled)
  [❌] Baubles-1.12-1.5.2.jar (disabled)
  [❌] BetterCombat-1.12.2-1.5.6.jar (disabled)
  [❌] betterwithspartanry-0.02.jar (disabled)
  [✔️] bewitchment-1.12.2-0.0.21.7
  [❌] BiblioCraft[v2.4.5][MC1.12.2].jar (disabled)
  [❌] BiomesOPlenty-1.12.2-7.0.1.2441-universal.jar (disabled)
  [❌] blockcraftery-1.12.2-1.3.1.jar (disabled)
  [❌] BloodMagic-1.12.2-2.4.3-105.jar (disabled)
  [❌] Botania r1.10-363.jar (disabled)
  [❌] BuildingGadgets-2.7.4.jar (disabled)
  [❌] Chisel-MC1.12.2-1.0.1.44.jar (disabled)
  [❌] CodeChickenLib-1.12.2-3.2.3.358-universal.jar (disabled)
  [❌] comforts-1.12.2-1.4.1.2.jar (disabled)
  [❌] crossroads-1.12.2-1.12.2.jar (disabled)
  [❌] CTM-MC1.12.2-1.0.1.30.jar (disabled)
  [❌] dartcraftreloaded-1.12.2-6.0.0-EOL.jar (disabled)
  [❌] defiledlands-1.12.2-1.4.3.jar (disabled)
  [❌] dimensionalpocketsii-1.12.2-3.1.34-beta-universal.jar (disabled)
  [❌] DoomlikeDungeons-1.12.10-MC1.12.2.jar (disabled)
  [❌] DungeonTactics-1.12.2-0.16.6.jar (disabled)
  [❌] ElectroblobsWizardry-4.2.8-MC1.12.2.jar (disabled)
  [❌] Embersified-1.12.2-1.0.3.jar (disabled)
  [❌] EmbersRekindled-1.13-hotfix2.jar (disabled)
  [❌] EnchantmentDescriptions-1.12.2-1.1.15.jar (disabled)
  [❌] essentials-1.12.2-1.2.1.jar (disabled)
  [❌] extraanvils-0.9.jar (disabled)
  [❌] ExtraSpells-1.12.2-1.1.4.jar (disabled)
  [❌] flying_things-1.5.2-1.12.jar (disabled)
  [❌] forbidden_arcanus-1.12.2-1.1.4.jar (disabled)
  [❌] Forgelin-1.8.4.jar (disabled)
  [❌] FTBBackups-1.1.0.1.jar (disabled)
  [❌] FTBLib-5.4.4.5.jar (disabled)
  [❌] FTBQuests-1.8.0.237.jar (disabled)
  [❌] FTBUtilities-5.4.0.124.jar (disabled)
  [❌] Guide-API-1.12-2.1.8-63.jar (disabled)
  [❌] iceandfire-1.8.3.jar (disabled)
  [❌] iChunUtil-1.12.2-7.2.2.jar (disabled)
  [❌] InfernalMobs-1.12.2.jar (disabled)
  [❌] ItemFilters-1.0.3.12.jar (disabled)
  [❌] jei_1.12.2-4.15.0.291.jar (disabled)
  [❌] JustEnoughResources-1.12.2-0.9.2.60.jar (disabled)
  [❌] lemonlib-1.12.2-1.3.0.jar (disabled)
  [❌] librarianlib-1.12.2-4.20-release.jar (disabled)
  [❌] llibrary-1.7.19-1.12.2.jar (disabled)
  [❌] lostmagic-1.0.1.jar (disabled)
  [❌] Mantle-1.12-1.3.3.55.jar (disabled)
  [📁] memory_repo (folder)
  [❌] mowziesmobs-1.5.4.jar (disabled)
  [✔️] mysticallib-1.12.2-1.6.0
  [❌] mysticalworld-1.12.2-1.7.1.jar (disabled)
  [❌] NoFov-MC1.12-1.0.1.jar (disabled)
  [❌] NomadicTents-1.12.2-9.5.2.jar (disabled)
  [❌] overpoweredarmorbar-1.12.2-0.3.2.jar (disabled)
  [✔️] Patchouli-1.0-20
  [❌] Placebo-1.12.2-1.6.0.jar (disabled)
  [❌] planarartifice-0.13.jar (disabled)
  [❌] plantswizardry-1.0.jar (disabled)
  [❌] plustic-7.1.6.1.jar (disabled)
  [❌] PotionCore-1.8_for_1.12.2.jar (disabled)
  [❌] QualityTools-1.0.7_for_1.12.2.jar (disabled)
  [❌] QuarkOddities-1.12.2.jar (disabled)
  [❌] Quark-r1.6-177.jar (disabled)
  [❌] reauth-3.6.0.jar (disabled)
  [❌] Reliquary-1.12.2-1.3.4.796.jar (disabled)
  [❌] RoguelikeDungeons-1.12.2-1.8.0.jar (disabled)
  [❌] Roots-1.12.2-3.0.24.jar (disabled)
  [❌] Rustic Thaumaturgy-4.4a.jar (disabled)
  [❌] rustic-1.1.2.jar (disabled)
  [❌] rusticbopwoods-1.0.jar (disabled)
  [❌] rusticwitcraft-1.0.2.jar (disabled)
  [❌] sharetome-1.0.jar (disabled)
  [❌] signpost-1.12-1.06.1.jar (disabled)
  [❌] somanyenchantments V0.4.31.jar (disabled)
  [❌] spartanfire-0.07.jar (disabled)
  [❌] SpartanShields-1.12.2-1.5.4.jar (disabled)
  [❌] SpartanWeaponry-1.12.2-beta-1.3.8.jar (disabled)
  [❌] SpartanWeaponryArcana-1.12.2-beta-1.0.3.jar (disabled)
  [❌] stg-1.12.2-1.2.3.jar (disabled)
  [❌] TConstruct-1.12.2-2.13.0.171.jar (disabled)
  [❌] Thaumcraft-1.12.2-6.1.BETA26.jar (disabled)
  [❌] Thaumic_Gadgets_1.12.2_0.1.5.1_tb.26.jar (disabled)
  [❌] ThaumicAugmentation-1.12.2-1.1.13.jar (disabled)
  [❌] ThaumicInventoryScanning_1.12.2-2.0.10.jar (disabled)
  [❌] thaumicperiphery-0.3.1.jar (disabled)
  [❌] ThaumicRestoration-1.3.2.jar (disabled)
  [❌] TheBetweenlands-3.5.6-universal.jar (disabled)
  [❌] TinkerToolLeveling-1.12.2-1.1.0.jar (disabled)
  [❌] Totemic-1.12.2-0.11.6.jar (disabled)
  [❌] twilightforest-1.12.2-3.10.1013-universal.jar (disabled)
  [❌] UnlimitedChiselWorks-0.3.4.jar (disabled)
  [❌] Vampirism-1.12.2-1.5.7.jar (disabled)
  [❌] VampirismIntegrations-1.12.2-1.2.0.jar (disabled)
  [❌] VanillaFix-1.0.10-99.jar (disabled)
  [❌] vanillafoodpantry-mc1.12.2-4.3.1.jar (disabled)
  [❌] VariedCommodities_1.12.2(21nov19).jar (disabled)
  [❌] VillageNames-1.12.2-3.2.3.jar (disabled)
  [❌] Waystones_1.12.2-4.1.0.jar (disabled)
  [❌] wizardry-0.10.8.jar (disabled)
  [❌] zeherlib-1.12.2-4.1.24-universal.jar (disabled)

Params:
  --username  --version MultiMC5 --gameDir I:/MC/mmc-stable-win32/MultiMC/instances/1.12.23/.minecraft --assetsDir I:/MC/mmc-stable-win32/MultiMC/assets --assetIndex 1.12 --uuid  --accessToken  --userType  --versionType release --tweakClass net.minecraftforge.fml.common.launcher.FMLTweaker

Window size: 854 x 480

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms512m, -Xmx5024m, -Duser.language=en]

Minecraft process ID: 8776

Using onesix launcher.

[13:58:37] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[13:58:37] [main/INFO] [LaunchWrapper]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[13:58:37] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLTweaker
[13:58:37] [main/INFO] [FML]: Forge Mod Loader version 14.23.5.2847 for Minecraft 1.12.2 loading
[13:58:37] [main/INFO] [FML]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_181, running on Windows 8.1:amd64:6.3, installed at C:\Program Files\Java\jre1.8.0_181
[13:58:37] [main/WARN] [FML]: The coremod FMLCorePlugin (net.minecraftforge.fml.relauncher.FMLCorePlugin) is not signed!
[13:58:37] [main/WARN] [FML]: The coremod FMLForgePlugin (net.minecraftforge.classloading.FMLForgePlugin) is not signed!
[13:58:37] [main/INFO] [FML]: Searching I:\MC\mmc-stable-win32\MultiMC\instances\1.12.23\.minecraft\mods for mods
[13:58:37] [main/INFO] [FML]: Searching I:\MC\mmc-stable-win32\MultiMC\instances\1.12.23\.minecraft\mods\1.12.2 for mods
[13:58:37] [main/INFO] [FML]: Loading tweaker org.spongepowered.asm.launch.MixinTweaker from arcanearchives-0.2.0.14.jar
[13:58:37] [main/INFO] [FML]: Loading tweaker org.spongepowered.asm.launch.MixinTweaker from bewitchment-1.12.2-0.0.21.7.jar
[13:58:37] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[13:58:37] [main/INFO] [LaunchWrapper]: Loading tweak class name org.spongepowered.asm.launch.MixinTweaker
[13:58:37] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:199]: Failed to start Minecraft:
[13:58:37] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:231]: java.lang.reflect.InvocationTargetException
[13:58:37] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:231]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[13:58:37] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:231]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[13:58:37] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:231]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[13:58:37] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:231]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[13:58:37] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:231]: 	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
[13:58:37] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:231]: 	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
[13:58:37] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:231]: 	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
[13:58:37] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:231]: 	at org.multimc.EntryPoint.main(EntryPoint.java:34)
[13:58:37] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: Caused by: java.util.ServiceConfigurationError: org.spongepowered.asm.service.IMixinServiceBootstrap: Provider org.spongepowered.asm.service.modlauncher.MixinServiceModLauncherBootstrap could not be instantiated
[13:58:37] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at java.util.ServiceLoader.fail(Unknown Source)
[13:58:37] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at java.util.ServiceLoader.access$100(Unknown Source)
[13:58:37] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at java.util.ServiceLoader$LazyIterator.nextService(Unknown Source)
[13:58:37] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at java.util.ServiceLoader$LazyIterator.access$700(Unknown Source)
[13:58:37] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at java.util.ServiceLoader$LazyIterator$2.run(Unknown Source)
[13:58:37] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at java.security.AccessController.doPrivileged(Native Method)
[13:58:37] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at java.util.ServiceLoader$LazyIterator.next(Unknown Source)
[13:58:37] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at java.util.ServiceLoader$1.next(Unknown Source)
[13:58:37] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at org.spongepowered.asm.service.MixinService.runBootServices(MixinService.java:77)
[13:58:37] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at org.spongepowered.asm.service.MixinService.<init>(MixinService.java:72)
[13:58:37] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at org.spongepowered.asm.service.MixinService.getInstance(MixinService.java:92)
[13:58:37] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at org.spongepowered.asm.service.MixinService.boot(MixinService.java:102)
[13:58:37] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at org.spongepowered.asm.launch.MixinBootstrap.<clinit>(MixinBootstrap.java:76)
[13:58:37] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at org.spongepowered.asm.launch.MixinTweaker.<init>(MixinTweaker.java:44)
[13:58:37] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[13:58:37] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
[13:58:37] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
[13:58:37] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at java.lang.reflect.Constructor.newInstance(Unknown Source)
[13:58:37] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at java.lang.Class.newInstance(Unknown Source)
[13:58:37] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:98)
[13:58:37] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[13:58:37] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	... 8 more
[13:58:37] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: Caused by: java.lang.SecurityException: class "org.spongepowered.asm.service.ServiceInitialisationException"'s signer information does not match signer information of other classes in the same package
[13:58:37] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at java.lang.ClassLoader.checkCerts(Unknown Source)
[13:58:37] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at java.lang.ClassLoader.preDefineClass(Unknown Source)
[13:58:37] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at java.lang.ClassLoader.defineClass(Unknown Source)
[13:58:37] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at java.security.SecureClassLoader.defineClass(Unknown Source)
[13:58:37] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at java.net.URLClassLoader.defineClass(Unknown Source)
[13:58:37] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at java.net.URLClassLoader.access$100(Unknown Source)
[13:58:37] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at java.net.URLClassLoader$1.run(Unknown Source)
[13:58:37] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at java.net.URLClassLoader$1.run(Unknown Source)
[13:58:37] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at java.security.AccessController.doPrivileged(Native Method)
[13:58:37] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at java.net.URLClassLoader.findClass(Unknown Source)
[13:58:37] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[13:58:37] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
[13:58:37] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[13:58:37] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at java.lang.Class.getDeclaredConstructors0(Native Method)
[13:58:37] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at java.lang.Class.privateGetDeclaredConstructors(Unknown Source)
[13:58:37] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at java.lang.Class.getConstructor0(Unknown Source)
[13:58:37] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at java.lang.Class.newInstance(Unknown Source)
[13:58:37] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	... 27 more
[13:58:37] [main/INFO] [STDOUT]: [org.multimc.EntryPoint:main:37]: Exiting with -1
[13:58:37] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: net.minecraftforge.fml.relauncher.FMLSecurityManager$ExitTrappedException
[13:58:37] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraftforge.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:49)
[13:58:37] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.SecurityManager.checkExit(Unknown Source)
[13:58:37] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.Runtime.exit(Unknown Source)
[13:58:37] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.System.exit(Unknown Source)
[13:58:37] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at org.multimc.EntryPoint.main(EntryPoint.java:38)
Exception in thread "main"

**Comment by noobanidus** [comment]
If you could post the error report on gist.github.com next time, that would be appreciated.

By the look of it, signed versions of Sponge's Mixins are being shipped with two separate mods, which is the correct way to do things, but it looks like the shading is failing on one end as the entire point of shading is to repack it with different package names to prevent issues like this.

I'll double-check our shading code.
