### ISSUE TITLE
Crash on Startup after latest update

### ISSUE THREAD

**Issue by renadi** [AranaiRa/ArcaneArchives#91]
Get this crash upon t rying to start with the latest update.

`java.lang.IllegalAccessError: tried to access class org.spongepowered.asm.mixin.transformer.MixinTransformer from class net.minecraftforge.fml.common.Loader
	at net.minecraftforge.fml.common.Loader.handler$zza000$beforeConstructingMods(Loader.java:1132)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:594)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:232)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)`

**Comment by noobanidus** [comment]
Please revert to the previous version. There is incompatibility with some mods with the current version using older versions of Mixins, and then incompatibility with that version with older versions of Mixins. It's really confusing, but there's no need to update to 0.2.0.17 in your case.
